version: "3.8"
services:
  reversi-backend:
    container_name: backend
    build: ./backend
    restart: "unless-stopped"
    ports:
      - "8888:8888"
    
  reversi-fontend:
    container_name: frontend
    build: ./frontend
    restart: "unless-stopped"
    ports:
      - "4242:3000"
