version: "3.8"
services:
  reversi-backend:
    container_name: backend
    build: ./backend
    restart: "unless-stopped"
    ports:
      - "8888:8888"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  reversi-fontend:
    container_name: frontend
    build: ./frontend
    restart: "unless-stopped"
    ports:
      - "4242:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  db:
    container_name: postgresql
    image: postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: reversi
      POSTGRES_PASSWORD: secr33t
      POSTGRES_DB: reversi_db
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
