version: "3.8"
services:
  reversi-backend:
    container_name: backend
    build: ./backend/Dockerfile
    restart: "unless-stopped"
    ports:
      - "8888:8888"
    
  reversi-fontend:
    container_name: frontend
    build: ./frontend/Dockerfile
    restart: "unless-stopped"
    ports:
      - "3000:3000"
